tool_ID = "native:renamelayer"
tool_name = "renamelayer"
brief_description = """Renames a layer."""
full_description = """Renames a layer."""
parameters = """
INPUT: Layer. Layer to rename. Type: [layer]
NAME: New name. The new name of the layer. Type: [string] outputs = 
OUTPUT: Layer. The (renamed) output layer. Type: [same as input]

"""
code_example = """
import processing
from qgis.core import QgsVectorLayer, QgsProject

def rename_layer():
    # Define the input and output paths
    input_path = 'D:/input_layer.shp'
    # Load the input layer
    input_layer = QgsVectorLayer(input_path, """Layer to rename", "ogr")
    
                             
    rename_params = {
        'INPUT': input_layer,
        'NAME': 'NewLayerName'                          
    }
    
                                   
    processing.run("native:renamelayer", rename_params)
    
                      
rename_layer()
"""
